/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessgame;

import id.co.indocyber.guessgame.model.WordModel;
import id.co.indocyber.guessgame.model.WordQuestionGenerator;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author user
 */
public class gueesgame extends javax.swing.JFrame {

//    String basicWord;
//    String [] bankSoal= {"Taman Anggrek", "Semanggi", "Kokas"};
    WordModel basicWord;
//    WordModel soal1 = new WordModel("Taman Anggrek", "Daerah di Jakarta Barat");
//    WordModel soal2 = new WordModel("Sudirman", "Jalan Utama di Jakarta");
//    WordModel soal3 = new WordModel("Tugu Tani", "Patung yang Dekat Monas");
//    WordModel soal4 = new WordModel("Citos", "Mall Di Depok");
//    WordModel soal5 = new WordModel("Gandaria City", "Mall Anak Muda ");
//    WordModel[] bankSoal = {soal1, soal2, soal3, soal4, soal5};

    List<WordModel> bankSoal;
    
    //    
    /**
     * Creates new form gueesgame
     */
    public gueesgame() {
        bankSoal = WordQuestionGenerator.createQuestionCollections();
        //basicWord = "Buaya Darat";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalField = new javax.swing.JTextField();
        jawabanField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkAnswerButton = new javax.swing.JButton();
        commentLabel = new javax.swing.JLabel();
        starButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalField.setEnabled(false);

        jawabanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jawabanFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban");

        checkAnswerButton.setText("Proses");
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        commentLabel.setText("Belum Ada Jawaban");

        starButton.setText("Mulai");
        starButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("hint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(starButton)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jawabanField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soalField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(checkAnswerButton))
                                .addComponent(hintLabel)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starButton)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soalField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jawabanField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAnswerButton)
                .addGap(18, 18, 18)
                .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jawabanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jawabanFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jawabanFieldActionPerformed

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
        // TODO add your handling code here:

        String jawaban = jawabanField.getText().trim();
        basicWord.setJawaban(jawaban);
        if (basicWord.cekJawaban()) {
            commentLabel.setText("You Win");
        } else {
            commentLabel.setText("Please try again");
        }
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    private void starButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starButtonActionPerformed
        // TODO add your handling code here:
        int soalindex = (int) Math.floor(Math.random() * bankSoal.size());
        System.out.println("index" + soalindex);
        basicWord = bankSoal.get(soalindex);
     
        System.out.println(basicWord.getBasicWord());
        soalField.setText(basicWord.acakHuruf());
        hintLabel.setText(basicWord.getHint());


    }//GEN-LAST:event_starButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gueesgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gueesgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gueesgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gueesgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gueesgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jawabanField;
    private javax.swing.JTextField soalField;
    private javax.swing.JButton starButton;
    // End of variables declaration//GEN-END:variables
}
